<a href="https://colab.research.google.com/github/BeLeap/nlp-prac/blob/main/02/09_Splitting-Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
X, y = zip(['a', 1], ['b', 2], ['c', 3])
X, y

(('a', 'b', 'c'), (1, 2, 3))

In [15]:
sequences = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)
X, y

(('a', 'b', 'c'), (1, 2, 3))

In [16]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

import pandas as pd

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [17]:
X = df['메일 본문']
y = df['스팸 메일 유무']

X.to_list(), y.to_list()

(['당신에게 드리는 마지막 혜택!',
  '내일 뵐 수 있을지 확인 부탁드...',
  '도연씨. 잘 지내시죠? 오랜만입...',
  '(광고) AI로 주가를 예측할 수 있다!'],
 [1, 0, 0, 1])

In [18]:
import numpy as np

np_array = np.arange(0, 16).reshape((4, 4))
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
X = np_array[:, :3]
y = np_array[:, 3]

X, y

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([ 3,  7, 11, 15]))

In [21]:
%pip install scikit-learn

In [23]:
X, y = np.arange(10).reshape((5, 2)), range(5)
X, list(y)

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), [0, 1, 2, 3, 4])

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)
X_train, X_test, y_train, y_test

(array([[2, 3],
        [4, 5],
        [6, 7]]), array([[8, 9],
        [0, 1]]), [1, 2, 3], [4, 0])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
y_train, y_test

([4, 0, 3], [2, 1])